[tool.poetry]
name = "ppoga-project"
version = "0.1.0"
description = "PPoGA (Predictive Plan-on-Graph with Action) - Advanced KG reasoning system"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "ppoga_project", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
openai = ">=1.35.0"
langchain = ">=0.3.27,<0.4.0"
langchain-openai = ">=0.3.34,<0.4.0"
langgraph = ">=0.6.8,<0.7.0"
requests = ">=2.32.5,<3.0.0"
beautifulsoup4 = ">=4.14.2,<5.0.0"
pandas = ">=2.3.3,<3.0.0"
numpy = ">=2.3.3,<3.0.0"
python-dotenv = ">=1.1.1,<2.0.0"
SPARQLWrapper = ">=2.0.0,<3.0.0"
sentence-transformers = ">=2.2.0,<3.0.0"
tqdm = ">=4.66.0,<5.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
