[tool.poetry]
name = "ppoga-project"
version = "0.1.0"
description = "PPoGA (Predictive Plan-on-Graph with Action) - Advanced KG reasoning system"
authors = ["PPoGA Team <ppoga@example.com>"]
readme = "README.md"
packages = [{include = "ppoga_project", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.35.0"
requests = "^2.32.0"
beautifulsoup4 = "^4.14.0"
pandas = "^2.3.0"
numpy = "^2.3.0"
python-dotenv = "^1.1.0"
SPARQLWrapper = "^2.0.0"
sentence-transformers = "^2.2.0"
tqdm = "^4.66.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.0.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
